// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct CameraLensCapabilities {
  /// Focal length of the lens in millimetres.
  var focalLength: Double? = nil
  /// Maximum aperture of the lens as an f-number (e.g. 1.8 means f/1.8).
  var aperture: Double? = nil
  /// Horizontal field of view in degrees.
  var fieldOfView: Double? = nil
  /// Minimum supported zoom factor (optical + digital).
  var minZoomFactor: Double? = nil
  /// Maximum supported zoom factor (optical + digital).
  var maxZoomFactor: Double? = nil
  /// Smallest step by which exposure compensation can be changed (in EV).
  var exposureOffsetStepSize: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CameraLensCapabilities? {
    let focalLength: Double? = nilOrValue(pigeonVar_list[0])
    let aperture: Double? = nilOrValue(pigeonVar_list[1])
    let fieldOfView: Double? = nilOrValue(pigeonVar_list[2])
    let minZoomFactor: Double? = nilOrValue(pigeonVar_list[3])
    let maxZoomFactor: Double? = nilOrValue(pigeonVar_list[4])
    let exposureOffsetStepSize: Double? = nilOrValue(pigeonVar_list[5])

    return CameraLensCapabilities(
      focalLength: focalLength,
      aperture: aperture,
      fieldOfView: fieldOfView,
      minZoomFactor: minZoomFactor,
      maxZoomFactor: maxZoomFactor,
      exposureOffsetStepSize: exposureOffsetStepSize
    )
  }
  func toList() -> [Any?] {
    return [
      focalLength,
      aperture,
      fieldOfView,
      minZoomFactor,
      maxZoomFactor,
      exposureOffsetStepSize,
    ]
  }
}

private class CameraInfoApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CameraLensCapabilities.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CameraInfoApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CameraLensCapabilities {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CameraInfoApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CameraInfoApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CameraInfoApiPigeonCodecWriter(data: data)
  }
}

class CameraInfoApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CameraInfoApiPigeonCodec(readerWriter: CameraInfoApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CameraCapabilitiesHostApi {
  /// Returns optical capabilities for every camera available on the device.
  func getCameraCapabilities() throws -> [CameraLensCapabilities]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CameraCapabilitiesHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CameraInfoApiPigeonCodec.shared }
  /// Sets up an instance of `CameraCapabilitiesHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CameraCapabilitiesHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns optical capabilities for every camera available on the device.
    let getCameraCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camera_info.CameraCapabilitiesHostApi.getCameraCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCameraCapabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCameraCapabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCameraCapabilitiesChannel.setMessageHandler(nil)
    }
  }
}
