// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Which side of the device a camera faces.
enum CameraLensPosition: Int {
  case front = 0
  case back = 1
  case external = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct IosCameraLensInfo {
  /// 35mm equivalent focal length, derived from AVCaptureDevice.Format.videoFieldOfView.
  var equivalentFocalLength: Double
  /// Minimum zoom factor. AVCaptureDevice.minAvailableVideoZoomFactor.
  var minZoomFactor: Double
  /// Maximum zoom factor. AVCaptureDevice.maxAvailableVideoZoomFactor.
  var maxZoomFactor: Double
  /// Minimum exposure offset in EV. AVCaptureDevice.minExposureTargetBias.
  var minExposureOffset: Double
  /// Maximum exposure offset in EV. AVCaptureDevice.maxExposureTargetBias.
  var maxExposureOffset: Double
  /// Which side of the device this camera faces. AVCaptureDevice.position.
  var position: CameraLensPosition
  /// True if this is the main (wide-angle back) camera. AVCaptureDevice.default(.builtInWideAngleCamera, for: .video, position: .back).
  var isMain: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IosCameraLensInfo? {
    let equivalentFocalLength = pigeonVar_list[0] as! Double
    let minZoomFactor = pigeonVar_list[1] as! Double
    let maxZoomFactor = pigeonVar_list[2] as! Double
    let minExposureOffset = pigeonVar_list[3] as! Double
    let maxExposureOffset = pigeonVar_list[4] as! Double
    let position = CameraLensPosition(rawValue: pigeonVar_list[5] as! Int)!
    let isMain = pigeonVar_list[6] as! Bool

    return IosCameraLensInfo(
      equivalentFocalLength: equivalentFocalLength,
      minZoomFactor: minZoomFactor,
      maxZoomFactor: maxZoomFactor,
      minExposureOffset: minExposureOffset,
      maxExposureOffset: maxExposureOffset,
      position: position,
      isMain: isMain
    )
  }
  func toList() -> [Any?] {
    return [
      equivalentFocalLength,
      minZoomFactor,
      maxZoomFactor,
      minExposureOffset,
      maxExposureOffset,
      position.rawValue,
      isMain,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AndroidCameraLensInfo {
  /// 35mm equivalent focal length. Null if LENS_INFO_AVAILABLE_FOCAL_LENGTHS or SENSOR_INFO_PHYSICAL_SIZE is unavailable.
  var equivalentFocalLength: Double? = nil
  /// Minimum zoom factor. 1.0 for the main back camera; null for other cameras.
  var minZoomFactor: Double? = nil
  /// Maximum zoom factor. CameraCharacteristics.SCALER_AVAILABLE_MAX_DIGITAL_ZOOM.
  var maxZoomFactor: Double
  /// Minimum exposure offset in EV. CONTROL_AE_COMPENSATION_RANGE.lower × CONTROL_AE_COMPENSATION_STEP.
  var minExposureOffset: Double
  /// Maximum exposure offset in EV. CONTROL_AE_COMPENSATION_RANGE.upper × CONTROL_AE_COMPENSATION_STEP.
  var maxExposureOffset: Double
  /// Smallest EV step for exposure compensation. CameraCharacteristics.CONTROL_AE_COMPENSATION_STEP.
  var exposureOffsetStepSize: Double
  /// Which side of the device this camera faces. CameraCharacteristics.LENS_FACING.
  var position: CameraLensPosition
  /// True if this is the main (first back-facing) camera. Camera ID matches the first LENS_FACING_BACK camera in cameraIdList.
  var isMain: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AndroidCameraLensInfo? {
    let equivalentFocalLength: Double? = nilOrValue(pigeonVar_list[0])
    let minZoomFactor: Double? = nilOrValue(pigeonVar_list[1])
    let maxZoomFactor = pigeonVar_list[2] as! Double
    let minExposureOffset = pigeonVar_list[3] as! Double
    let maxExposureOffset = pigeonVar_list[4] as! Double
    let exposureOffsetStepSize = pigeonVar_list[5] as! Double
    let position = CameraLensPosition(rawValue: pigeonVar_list[6] as! Int)!
    let isMain = pigeonVar_list[7] as! Bool

    return AndroidCameraLensInfo(
      equivalentFocalLength: equivalentFocalLength,
      minZoomFactor: minZoomFactor,
      maxZoomFactor: maxZoomFactor,
      minExposureOffset: minExposureOffset,
      maxExposureOffset: maxExposureOffset,
      exposureOffsetStepSize: exposureOffsetStepSize,
      position: position,
      isMain: isMain
    )
  }
  func toList() -> [Any?] {
    return [
      equivalentFocalLength,
      minZoomFactor,
      maxZoomFactor,
      minExposureOffset,
      maxExposureOffset,
      exposureOffsetStepSize,
      position.rawValue,
      isMain,
    ]
  }
}

private class CameraInfoApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return IosCameraLensInfo.fromList(self.readValue() as! [Any?])
    case 130:
      return AndroidCameraLensInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CameraInfoApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? IosCameraLensInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? AndroidCameraLensInfo {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CameraInfoApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CameraInfoApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CameraInfoApiPigeonCodecWriter(data: data)
  }
}

class CameraInfoApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CameraInfoApiPigeonCodec(readerWriter: CameraInfoApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CameraInfoIosHostApi {
  /// Returns optical info for every camera available on the device (iOS).
  func getCameraInfo() throws -> [IosCameraLensInfo]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CameraInfoIosHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CameraInfoApiPigeonCodec.shared }
  /// Sets up an instance of `CameraInfoIosHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CameraInfoIosHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns optical info for every camera available on the device (iOS).
    let getCameraInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camera_info.CameraInfoIosHostApi.getCameraInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCameraInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCameraInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCameraInfoChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CameraInfoAndroidHostApi {
  /// Returns optical info for every camera available on the device (Android).
  func getCameraInfo() throws -> [AndroidCameraLensInfo]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CameraInfoAndroidHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CameraInfoApiPigeonCodec.shared }
  /// Sets up an instance of `CameraInfoAndroidHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CameraInfoAndroidHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns optical info for every camera available on the device (Android).
    let getCameraInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.camera_info.CameraInfoAndroidHostApi.getCameraInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCameraInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCameraInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCameraInfoChannel.setMessageHandler(nil)
    }
  }
}
