// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.vodemn.camera_info

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class CameraLensCapabilities (
  /** Focal length of the lens in millimetres. */
  val focalLength: Double? = null,
  /** Maximum aperture of the lens as an f-number (e.g. 1.8 means f/1.8). */
  val aperture: Double? = null,
  /** Horizontal field of view in degrees. */
  val fieldOfView: Double? = null,
  /** Minimum supported zoom factor (optical + digital). */
  val minZoomFactor: Double? = null,
  /** Maximum supported zoom factor (optical + digital). */
  val maxZoomFactor: Double? = null,
  /** Smallest step by which exposure compensation can be changed (in EV). */
  val exposureOffsetStepSize: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraLensCapabilities {
      val focalLength = pigeonVar_list[0] as Double?
      val aperture = pigeonVar_list[1] as Double?
      val fieldOfView = pigeonVar_list[2] as Double?
      val minZoomFactor = pigeonVar_list[3] as Double?
      val maxZoomFactor = pigeonVar_list[4] as Double?
      val exposureOffsetStepSize = pigeonVar_list[5] as Double?
      return CameraLensCapabilities(focalLength, aperture, fieldOfView, minZoomFactor, maxZoomFactor, exposureOffsetStepSize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      focalLength,
      aperture,
      fieldOfView,
      minZoomFactor,
      maxZoomFactor,
      exposureOffsetStepSize,
    )
  }
}
private open class CameraInfoApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraLensCapabilities.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CameraLensCapabilities -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CameraCapabilitiesHostApi {
  /** Returns optical capabilities for every camera available on the device. */
  fun getCameraCapabilities(): List<CameraLensCapabilities>

  companion object {
    /** The codec used by CameraCapabilitiesHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CameraInfoApiPigeonCodec()
    }
    /** Sets up an instance of `CameraCapabilitiesHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CameraCapabilitiesHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.camera_info.CameraCapabilitiesHostApi.getCameraCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCameraCapabilities())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
