// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.vodemn.camera_info

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Which side of the device a camera faces. */
enum class CameraLensPosition(val raw: Int) {
  FRONT(0),
  BACK(1),
  EXTERNAL(2);

  companion object {
    fun ofRaw(raw: Int): CameraLensPosition? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Axis convention used for a 35mm-equivalent focal length. */
enum class EquivalentFocalLengthBasis(val raw: Int) {
  DIAGONAL(0),
  HORIZONTAL(1);

  companion object {
    fun ofRaw(raw: Int): EquivalentFocalLengthBasis? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class IosCameraLensInfo (
  /** Horizontal 35mm-equivalent focal length, or null when its horizontal FOV is unusable. */
  val equivalentFocalLength: Double? = null,
  /** Axis convention for this platform's EFL calculation: always horizontal on iOS. */
  val equivalentFocalLengthBasis: EquivalentFocalLengthBasis,
  /** Width / height of the active format used to convert this EFL to another axis. */
  val equivalentFocalLengthAspectRatio: Double? = null,
  /** Minimum zoom factor. AVCaptureDevice.minAvailableVideoZoomFactor. */
  val minZoomFactor: Double,
  /** Maximum zoom factor. AVCaptureDevice.maxAvailableVideoZoomFactor. */
  val maxZoomFactor: Double,
  /** Minimum exposure offset in EV. AVCaptureDevice.minExposureTargetBias. */
  val minExposureOffset: Double,
  /** Maximum exposure offset in EV. AVCaptureDevice.maxExposureTargetBias. */
  val maxExposureOffset: Double,
  /** Which side of the device this camera faces. AVCaptureDevice.position. */
  val position: CameraLensPosition,
  /** True if this is the main (wide-angle back) camera. AVCaptureDevice.default(.builtInWideAngleCamera, for: .video, position: .back). */
  val isMain: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IosCameraLensInfo {
      val equivalentFocalLength = pigeonVar_list[0] as Double?
      val equivalentFocalLengthBasis = pigeonVar_list[1] as EquivalentFocalLengthBasis
      val equivalentFocalLengthAspectRatio = pigeonVar_list[2] as Double?
      val minZoomFactor = pigeonVar_list[3] as Double
      val maxZoomFactor = pigeonVar_list[4] as Double
      val minExposureOffset = pigeonVar_list[5] as Double
      val maxExposureOffset = pigeonVar_list[6] as Double
      val position = pigeonVar_list[7] as CameraLensPosition
      val isMain = pigeonVar_list[8] as Boolean
      return IosCameraLensInfo(equivalentFocalLength, equivalentFocalLengthBasis, equivalentFocalLengthAspectRatio, minZoomFactor, maxZoomFactor, minExposureOffset, maxExposureOffset, position, isMain)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      equivalentFocalLength,
      equivalentFocalLengthBasis,
      equivalentFocalLengthAspectRatio,
      minZoomFactor,
      maxZoomFactor,
      minExposureOffset,
      maxExposureOffset,
      position,
      isMain,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AndroidCameraLensInfo (
  /** 35mm equivalent focal length. Null if LENS_INFO_AVAILABLE_FOCAL_LENGTHS or SENSOR_INFO_PHYSICAL_SIZE is unavailable. */
  val equivalentFocalLength: Double? = null,
  /** Axis convention for this platform's EFL calculation: always diagonal on Android. */
  val equivalentFocalLengthBasis: EquivalentFocalLengthBasis,
  /** Width / height of the physical sensor used for EFL geometry, when available. */
  val equivalentFocalLengthAspectRatio: Double? = null,
  /** Minimum zoom factor. 1.0 for the main back camera; null for other cameras. */
  val minZoomFactor: Double? = null,
  /** Maximum zoom factor. CameraCharacteristics.SCALER_AVAILABLE_MAX_DIGITAL_ZOOM. */
  val maxZoomFactor: Double,
  /** Minimum exposure offset in EV. CONTROL_AE_COMPENSATION_RANGE.lower × CONTROL_AE_COMPENSATION_STEP. */
  val minExposureOffset: Double,
  /** Maximum exposure offset in EV. CONTROL_AE_COMPENSATION_RANGE.upper × CONTROL_AE_COMPENSATION_STEP. */
  val maxExposureOffset: Double,
  /** Smallest EV step for exposure compensation. CameraCharacteristics.CONTROL_AE_COMPENSATION_STEP. */
  val exposureOffsetStepSize: Double,
  /** Which side of the device this camera faces. CameraCharacteristics.LENS_FACING. */
  val position: CameraLensPosition,
  /** True if this is the main (first back-facing) camera. Camera ID matches the first LENS_FACING_BACK camera in cameraIdList. */
  val isMain: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidCameraLensInfo {
      val equivalentFocalLength = pigeonVar_list[0] as Double?
      val equivalentFocalLengthBasis = pigeonVar_list[1] as EquivalentFocalLengthBasis
      val equivalentFocalLengthAspectRatio = pigeonVar_list[2] as Double?
      val minZoomFactor = pigeonVar_list[3] as Double?
      val maxZoomFactor = pigeonVar_list[4] as Double
      val minExposureOffset = pigeonVar_list[5] as Double
      val maxExposureOffset = pigeonVar_list[6] as Double
      val exposureOffsetStepSize = pigeonVar_list[7] as Double
      val position = pigeonVar_list[8] as CameraLensPosition
      val isMain = pigeonVar_list[9] as Boolean
      return AndroidCameraLensInfo(equivalentFocalLength, equivalentFocalLengthBasis, equivalentFocalLengthAspectRatio, minZoomFactor, maxZoomFactor, minExposureOffset, maxExposureOffset, exposureOffsetStepSize, position, isMain)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      equivalentFocalLength,
      equivalentFocalLengthBasis,
      equivalentFocalLengthAspectRatio,
      minZoomFactor,
      maxZoomFactor,
      minExposureOffset,
      maxExposureOffset,
      exposureOffsetStepSize,
      position,
      isMain,
    )
  }
}
private open class CameraInfoApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraLensPosition.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EquivalentFocalLengthBasis.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IosCameraLensInfo.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidCameraLensInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CameraLensPosition -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is EquivalentFocalLengthBasis -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is IosCameraLensInfo -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AndroidCameraLensInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CameraInfoIosHostApi {
  /** Returns optical info for every camera available on the device (iOS). */
  fun getCameraInfo(): List<IosCameraLensInfo>

  companion object {
    /** The codec used by CameraInfoIosHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CameraInfoApiPigeonCodec()
    }
    /** Sets up an instance of `CameraInfoIosHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CameraInfoIosHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.camera_info.CameraInfoIosHostApi.getCameraInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCameraInfo())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CameraInfoAndroidHostApi {
  /** Returns optical info for every camera available on the device (Android). */
  fun getCameraInfo(): List<AndroidCameraLensInfo>

  companion object {
    /** The codec used by CameraInfoAndroidHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CameraInfoApiPigeonCodec()
    }
    /** Sets up an instance of `CameraInfoAndroidHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CameraInfoAndroidHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.camera_info.CameraInfoAndroidHostApi.getCameraInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getCameraInfo())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
